development:
  adapter: postgresql
  encoding: unicode
  database: firehouse_development
  pool: 5
  username: docker
  password: docker
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: firehouse_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'docker' %>
  password: <%= ENV['TRAVIS'] ? '' : 'docker' %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_PROD_NAME'] %>
  pool: 5
  username: <%= ENV['DB_PROD_USR'] %>
  password: <%= ENV['DB_PROD_PWD'] %>
  host: <%= ENV['DB_PROD_HOST'] %>
